name: petadopt
on:
  push:
    branches:
      - '*'
    workflow_dispatch:
env:
  POSTGRES_DB: petadopt
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES-DB: ${{env.POSTGRES_DB}}
          POSTGRES-PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
      steps:
        - users: action/checkout@v3
        - run:
          yarn install
        working-directory: ./
      